### ISSUE TITLE
Create a new color hide external

### ISSUE THREAD

**Issue by joaosalvado10** [VisualDataWeb/WebVOWL#112]
Hello, I have 2 questions.

1. I would like to know if it is possible to hide the Charac.: external when an ontology is drawn.
2. I would like to know how to create a new color. I was only able to edit 3 of the existing ones.
Thank you.

**Comment by linkvt** [comment]
Hi,

1. There is no filter for filtering externals, you would have to write one that is similar to the [setOperatorFilter.js](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/webvowl/js/modules/setOperatorFilter.js). It is possible that there are e.g. external elements that are also deprecated, so to filter all elements that are colored as externals (blue) you could check whether the `visualAttributes` contain the `external` attribute similar to [here](https://github.com/VisualDataWeb/WebVOWL/blob/2f19b1d18e612e9391fbdc690804da584d48b09b/src/webvowl/js/modules/colorExternalsSwitch.js#L38-L43).
2. Almost all colors are defined in the [vowl.css](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/webvowl/css/vowl.css), an exception are external elements, because they might have dynamic coloring: [colorExternalsSwitch.js](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/webvowl/js/modules/colorExternalsSwitch.js#L7-L8). Which colors can't be changed?

Cheers

**Comment by joaosalvado10** [comment]
Ok thank you.

For instances, the external or the general.
So how to create a new one=?

Cheers

**Comment by linkvt** [comment]
IIRC you should be able to change the default color just as described in the [vowl.css](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/webvowl/css/vowl.css#L26) file - otherwise you would have to take a look at the provided JavaScript code and change the color codes.

Do you want to create a new color or a new filter?

**Comment by joaosalvado10** [comment]
I would like to create new filter different from external and deprecated , i would like to use them to fill up the balls.
Otherwise I would like to do the following:
When the ball is presented it is possible to see bellow  the name  this “(external)” or “(deprecated)”.
How do i remove this ?

**Comment by steffen-l** [comment]
@joaosalvado10: Please check out the features of the tool:

- you can hide this extra info simply by activating the option "compact notation" in the "mode" menu
- you can also deactivate the coloring of external nodes there (by deactivating the respective option)

If you require further customizations, either change the CSS styles or JavaScript code (as proposed by @linkvt). There is also the possibility of exporting the visualization as SVG image for further customization in the SVG editor of your choice.

**Comment by joaosalvado10** [comment]
@steffen-l that is exactly what I want. However I want it to be presented as default.
Where do i have to change to make the compact notation activated by default?

**Comment by steffen-l** [comment]
Glad to hear that. Just use the "Export as URL" feature and your settings will be added to the URL, e.g. in your case it adds "#opts=[mode_compact=true;]".

Enjoy!

**Comment by joaosalvado10** [comment]
Is there any other way to change in a code in such way that when the page is refreshed that option would be True by default.
I can not find in the code where it is being defined the default option as unchecked.

**Comment by steffen-l** [comment]
See https://github.com/VisualDataWeb/WebVOWL/blob/master/src/app/js/menu/modeMenu.js

Note that the option remains checked when you refreh the page - I assume you tried: http://visualdataweb.de/webvowl/#opts=[mode_compact=true;]

**Comment by joaosalvado10** [comment]
That is it, thank you guys
