### ISSUE TITLE
How can i disable the client side cache?

### ISSUE THREAD

**Issue by TroniPM** [VisualDataWeb/WebVOWL#139]
I need to remove front side cache at all. Without need to refresh the page (justo reload the same file). How can i accomplish that?

**Comment by vitalis-wiens** [comment]
If I understand you correct, you can do this by modifying the following code

File : src/app/js/menu/ontologyMenu.js
Line: 27 
Function:
 ontologyMenu.cachedOntology=function(ontoName){
		return cachedConversions[ontoName];
	};

If this function returns undefined, then the ontology is processed otherwise the cached version is loaded, 
so by modifing it like this:
ontologyMenu.cachedOntology=function(ontoName){
		//return cachedConversions[ontoName];
                return undefined;
};

should solve it

Kind Regards,
Vitalis

**Comment by TroniPM** [comment]
Perfect.I had to change webvowl.js: ```E.cachedOntology=function(e){return I[e];}``` to ```E.cachedOntology=function(e){return undefined;}```. This worked like a charm.
