### ISSUE TITLE
WebVOWL Module Exports and Overrides

### ISSUE THREAD

**Issue by sranger** [VisualDataWeb/WebVOWL#141]
We're trying to use WebVOWL but it doesn't seem to allow loading json object directly and only from a file. We modified the code to do what we need (but it's sort of a brute force change and not something you'd want to merge in). However, we don't want to support a fork if at all possible and would rather "extend" your library by replacing part of the loadingModules code. But, that module is not being exported when it's compiled into webvowl.app.js so the object is not accessible for us to extend/override. 

I'd like to know if there's a way to do what we're trying to do that I'm just not familiar with (I don't know webpack at all) or is this feature something that is planned to be added that we can just continue to use our fork for the time being and eventually update to the official implementation soon?

Thanks for the library and the help!

**Comment by sranger** [comment]
If that modification isn't within the scope of what the project wants to support can an option be added to export the modules to more easily allow external overriding?

**Comment by vitalis-wiens** [comment]
WebVOWL actually loads the text file and creates an JSON object
which is then used to create the graph

In app.js 
Line 237:
	data =JSON.parse(jsonText);
data is the json object which is then forwarded to graph

Line 281:
options.data(data);
...
graph.load();
            
graph.load uses the JSON object that is provided by options.data()

The loading module can be accessed using options.loadingModule()

We don`t plan to extend WebVOWL to provide a direct JSON object loading,
because the JSON object has to be in the memory of the client.
Our solution is to load ontologies that are converted to JSON files and these are then 
parsed and a JSON object is created that is then used to create the visualization.

**Comment by vitalis-wiens** [comment]
Hi, maybe I am just misunderstanding something.

1) From my point of view a JSON object is an JavaScript Object that is generated by JSON.parse(someText). So it has to be in the memory. 


2) Ontologies are text files, we convert these using OWL2VOWL into a string representation (JSON), and using JSON.parse(sometext) we have the JSON object in memory ( the variable data ) that is then forwarded to the graph .



The modules are exported, otherwise the program would not work
If you modify the index.html like this (Line 464)
  <script>
        window.onload = webvowl.app().initialize;
        console.log("AccessLibrary");
        console.log(webvowl.graph().options());
    </script>
You can access the options module which holds the loading module etc. 

An other question, that might help to clarify the issue:
How do you obtain the converted Ontology ? 
How do you create the JSON object ? 

Kind Regards, 
Vitalis

**Comment by sranger** [comment]
We create the JSON object within the page (our use case requires they're all embedded into the same file so we create the JSON object within the script tag of our output page). So we can't give you the text representation because we have the JSON object (that you get from JSON.parse)

As for the script; that's what we're doing. When we check Object.keys(webvowl.graph().options().loadingModule) it is just an empty array and webvowl.graph().options().loadingModule() is undefined.

**Comment by vitalis-wiens** [comment]
Hi, now I understand.

You were right the loadingModule and all others are indeed empty.
webvowl.graph() returns us the uninitialized  object. 

In order to get the initialized object, some modifications are required .

for example :  app.js
in initialize function at the end add the updated value for options 
   webvowl.uOpts=options;
and creating  a function 
app.getOptions=function(){
	    return webvowl.uOpts;
    };
This will return the updated options object; 
It holds then the initialized modules (loadingModule)

Regarding first saving the file: 
it is not required, you can directly create a string from the json obj you have created; 

var asString=JSON.stringify(myJsonObj);
webvowl.app().getOptions().loadingModule().directInput(asString)

Kind Regards, 
Vitalis

**Comment by sranger** [comment]
So we already have forked the code and made modifications for us to be able to load data directly but we'd rather not have to manage a fork if it were possible otherwise. Is there any way we can get this functionality officially added to the library at some point?

**Comment by vitalis-wiens** [comment]
We have released the newest version (1.1.3) 
it has now the access to the initialized objects.

options can accessed in the index.html via webvowl.opts
and the graph via webvowl.gr

You can use the direct input method to load your JsonObj
Just make sure that the app is initialized 

// Index.html : 
window.onload = webvowl.app().initialize; // this does not call the init function.
webvowl.app().initialize(); // initializes the app and grants access to opts and graph.

var loadingModule=webvowl.opts.loadingModule();
console.log(loadingModule); // now the loading module is accessible 

var asString=JSON.stringify(myJsonObj);
webvowl.opts.loadingModule().directInput(asString); 

Kind regards 
Vitalis
