### ISSUE TITLE
Importing valid OWL ontologies fails

### ISSUE THREAD

**Issue by flekschas** [VisualDataWeb/WebVOWL#16]
I tried to visualize a custom ontology (using the online [demo][http://vowl.visualdataweb.org/webvowl/index.html]) by importing through the IRI (http://purl.obolibrary.org/obo/ro.owl) but unfortunately the import fails and links me to the OWL validator even though the OWL validator confirms that the ontology together with all imports are valid OWL 2 profile. I got the same failure when uploading the file from my computer.

**Comment by linkvt** [comment]
Hi @flekschas,

sorry that you're having problems with visualizing this ontology.
The *Show error details* button in WebVOWL revealed, that the error occurred in [OWL2VOWL](/VisualDataWeb/OWL2VOWL). OWL2VOWL is used to convert the ontology into a JSON file WebVOWL can understand.

I'll open an issue there and reference this issue.
We are currently rewriting OWL2VOWL to be more stable and extendable, because the time OWL2VOWL was written nobody had a clue how the OWLApi has to be used correctly to extract the necessary information from the ontology.

Regards,
Vincent

**Comment by linkvt** [comment]
Opened an issue in the OWL2VOWL project

**Comment by flekschas** [comment]
Thanks for getting back so quickly, looking forward to a fix! I like your visualization. It's really smooth. Great work.

**Comment by linkvt** [comment]
Thanks for the feedback, always nice to hear. I'll pass it on to the others.
