### ISSUE TITLE
Coloring of external elements

### ISSUE THREAD

**Issue by steffen-l** [VisualDataWeb/WebVOWL#40]
- [x] Another color scheme for the coloring of external elements
- [x] Maybe an option to choose first "color externals" and then between "same color" and "color gradient"

**Comment by steffen-l** [comment]
New coloring looks good but a few issues

- [It does not work for external properties - see e.g. MUTO]
- [The dropdown box is not the most beautiful solution and also problematic, since it interferes with the WebVOWL menu - at least in Firefox. A switch element (for switching on the gradient) might be the better choice in this case]

**Comment by mpuebla** [comment]
Hello Mr. Steffen: 



Let me make a suggestion that could increase the use of "WebVOWL". 




As you know, I am a user of WebVOWL, however, I have noticed that are missing very important features for my needs, which are present in similar tools: OntoGraf and OWLViz. The problem is that none of these tools are on the Web, as WebVOWL. For that reason, I consider it very important that WebOWL allow the following features: 

1) 

Give the possibility, at the end user, go to expand the display level of ontology. That is, initially only the "Thing" class and its immediate subclasses are displayed, then users will have the option to decide whether to continue expanding ontology. This feature is vital when trying to display very large ontologies, with many classes and individuals. 



Grateful for your time. 



Best regards, Manuel Puebla.

**Comment by steffen-l** [comment]
Thanks for your feedback and suggestion. Please note that, although we have not implemented a local exploration feature into WebVOWL, it supports global collapsing of large ontologies. You find a slider in the "filter" menu that allows you to adapt the size of the ontology. The next version of WebVOWL (which will be released soon) will even automatically collapse large ontologies after they are loaded. I know this is not the same as a local exploration feature but will hopefully of help anyway. We can envision many more nice features for WebVOWL, but please understand that this an academic project without specific funding at the moment, so we have only very limited resources for it.

**Comment by jindrichmynarz** [comment]
Is it still valid that WebVOWL doesn't support per-node expansion? I haven't managed to find a way how to do it.
