### ISSUE TITLE
how to change name of class of rdfs:literal 

### ISSUE THREAD

**Issue by chy373** [VisualDataWeb/WebVOWL#43]
I change the label, but it doesn't work

**Comment by steffen-l** [comment]
Thanks for the feedback. However, I don't understand the issue. Could you please provide more infos?

**Comment by chy373** [comment]
@steffen-l thanks for your reply, I am sorry for my bad description about my problem, but I have solved my problem. However,  another problem bothered me, I will be grateful if U can give me some advice.

I noticed that WebVOWL read json with a path of json file(like '/data/foaf.json'), but I want to get json from an api that return json(like 'localhost:8000/api/')， how can I change the behaviour of getting json in ontologyMenu.js

**Comment by linkvt** [comment]
WebVOWL consists of a visualization and an app. The WebVOWL app allows shortcuts to a few selected visualizations like foaf (e.g. `webvowl.url/#foaf`).

If you dont wan't to access the preconverted and cached foaf ontology (via `/data/foaf.json`) you need to use another URL like `webvowl.url/#iri=http://xmlns.com/foaf/0.1/`.

The next step is to change the OWL2VOWL instance WebVOWL is using in [ontologyMenu.js#L90](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/app/js/menu/ontologyMenu.js#L90).
In your example you could maybe use `http://localhost:8000/api/` instead of `"convert?iri=`.

If its not convenient for you to use something like `webvowl.url/#iri=ontology` instead of `webvowl.url/#ontology` you need to make bigger adjustments to the `ontologyMenu.js` or the whole app, since its developed to meet the conditions of the official WebVOWL instance.
