### ISSUE TITLE
Need your help to add a new feature

### ISSUE THREAD

**Issue by phamlequang** [VisualDataWeb/WebVOWL#49]
Sorry for opening a new issue but I don't know where to post this. 

First, I must say that this is an awesome project. It helped me a lot to visualize my ontology on the web. 

However, I need to modify it a little bit to add one more feature: When the ontology is opened for the first time, it should only display one or a few important nodes, and if user clicks on a node, it will then expand the graph to show more nodes that has direct link to that clicked node.

I am reading your code to understand and to be able to change it, but I must admit that it is a huge project and I really need your help to know where should I focus on. 

Could you please spend some time to show me where should I read and modify the code to accomplish the task? I would be very grateful. 

Thank you.

**Comment by linkvt** [comment]
Hi,

it's nice to hear that WebVOWL is useful for you!

We wanted to implement a feature like this some time ago, too, but didn't continue the idea. The problem was, that we couldn't decide generically which nodes were important and finally focused on other features due to time constraints.
I totally understand that the code is not that readable due to the kind of project and its growth, but I hope I can guide you a bit to achieve what you want.

The data of the graph can be filtered by using modules, which also can be used to react on events like the selection of a node/property.
Example for the filter (`filter`-function): [datatypeFilter.js](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/webvowl/js/modules/datatypeFilter.js)
Example for click events (`handle`-function): [pickAndPin.js](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/webvowl/js/modules/pickAndPin.js)

You need to implement a module that has both a `filter` and a `handle`-function and add it to the graph in the [app.js](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/app/js/app.js) as filter and selection module.
By default this module should filter all but your important nodes by using the `filterTools.filterNodesAndTidy`-function as in the `datatypeFilter.js` example, which will also remove all properties which are connected to now filtered(=removed) nodes.
You could add these important nodes (or their ids) to a set or so.
When the `handle`-function is called, you should check if the clicked element is a node (similar as in the `pickAndPin.js`), use the `.links()` function on this node to get all links and add the connected nodes to the set.
You might need to call a `graph.update()` after clicking to (e.g. in your `handle`-function) to trigger filtering the data with your `filter`-function.

You can find the drawing of a button for the collapsible mode here in case you want to reuse it (using this instead of a simple click on the node would require a bit more effort): [RoundNode.js#L110-L139](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/webvowl/js/elements/nodes/RoundNode.js#L110-L139)
A skeleton of the module we wanted to use is here (at least at the moment, I will probably remove it in future commits because its unused): [collapsing.js](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/webvowl/js/modules/collapsing.js)

I hope this helps you implementing it. I'm not completely sure if this works out 100% as described, since I couldn't test it, but I think it should work like this.

**Comment by phamlequang** [comment]
linkvt: Thank you very much for your quick response and detailed explanation. I think it is quite clear now for me to understand and implement the feature.

**Comment by phamlequang** [comment]
Hi linkvt,

Thank you again for you help.

I successfully implemented the mentioned feature, which allows me to select a node and display only the nodes which is K (= 1, 2, 3, ..) level away (by Breadth First Search) from selected node.

However, when K > 1 the graph looks quite messy because of large number of nodes and links between them. That's why I need to add one more new feature: Redraw the graph as a tree-like structure, something like this image:
<img width="883" alt="screen shot 2016-04-29 at 9 45 56 am" src="https://cloud.githubusercontent.com/assets/5135005/14910620/5468520c-0def-11e6-8750-afcdf8e12a6a.png">

Do you think that it is possible to do so, and if it is, could you please guide me how to implement?
Thank you.

**Comment by linkvt** [comment]
Hi,

thats a difficult question, because I think it would be quite some work to implement it by yourself. I found this although after a bit of googling: http://bl.ocks.org/mbostock/1138500.
I added the `e` parameter to the `recalculatePositions`-function in `graph.js`, and changed this
```
		// Set link paths and calculate additional informations
		linkPathElements.attr("d", function (l) {
```
to this
```
		var alpha = !!e ? e.alpha : 1;
		var k = 6 * alpha;
		// Set link paths and calculate additional informations
		linkPathElements.each(function(d) { d.domain().y -= k, d.range().y += k; }).attr("d", function (l) {
```
I had to add an extra check because `recalculatePositions` is also called at another place where the event isn't available, but you can read more about that parameter here: https://github.com/mbostock/d3/wiki/Force-Layout#on

It seemed to do something with the graph I used, but since it wasn't really a tree it couldn't be visualized as one. It looks like your data should contain mostly edges that point in one direction to achieve the best results.
It might work better for you and seems to be the easiest approach.

**Comment by phamlequang** [comment]
Hi linkvt,

Thank you very much for your guide. I successfully implemented this feature. My strategy is simple: just consider the BFS-tree as the graph, so it is really a tree and the result looks quite good. 

However the nodes become quite closed to each other (and sometimes overlap each other), because we only modify Y without changing X. Do you have any idea how to solve this problem?

Thank you.

**Comment by linkvt** [comment]
Hi phamlequang,

nice to see that you found a way to make it work. I'm currently not sure if you use the way described above but I will assume it for the following.

You could try to increase the distance of the nodes by adjusting e.g. `classDistance` or `datatypeDistance` in the options file. This will increase the force with which the nodes repell each other.

You could also offset the nodes similar as in the example above by modifiying the `.x` value. If you know that there are 5 nodes on a specific level, you could offset the first two nodes to the left and the last two nodes to the right.

If it's just the overlaps that are a problem for you it should be sufficient to increase the `...Distance` values and let d3 to the rest.

**Comment by phamlequang** [comment]
Hi linkvt,

Thank you for your advice. I figured out a way to solve this problem: Iterate through all pair of visible nodes, and if 2 nodes are overlap, just modify their coordinates.

I need to ask you one more thing: I would like to display the relationship between instances (individuals), however it seems that the relationships between individuals were removed when I convert from OWL file to JSON file using OWL2VOWL. Can you confirm this? And if it's true, how can I still keep this information when converting?

Thank you.

**Comment by linkvt** [comment]
Hi,

I'm not 100% sure but I think we didn't intend to visualize relationships between individuals as stated in the [VOWL specification](http://vowl.visualdataweb.org/v2/):
> This specification focuses on the visualization of the ontology schema (i.e. the classes, properties and datatypes, sometimes called TBox), while it also includes recommendations on how to depict individuals and data values (the ABox).

I will also ask my fellow student who mainly develops OWL2VOWL. Please tell me if I misunderstood something or if you thing this should be handeled differently.

**Comment by phamlequang** [comment]
OK. Thank you.

**Comment by jorgeluceda** [comment]
Hi @linkvt , I've begun implementing a feature very similar to this, but I am running into a major issue. As you mentioned, I am calling the  links() function on the selected node to get all of the links, but it seems like the links() function only provides the links that are currently on the graph, not the ones that have been filtered. 

You can see the custom module I've made [https://github.com/jorgeluceda/WebVOWL-filtered/blob/master/src/webvowl/js/modules/filterAndHandle.js](here) (allow with the rest of the code in that repository), but the important part relating to this issue can be seen in the below snippet:

```   
if(elementTools.isNode(selection)) {
      var unfilteredNodeLinks;
      unfilteredNodes.forEach(function(node) {
        if(node.id() == selection.id()) {
          unfilteredNodeLinks = node.links();
        }
      });
      unfilteredNodeLinks.forEach(function(link) {
          //the amount of links pushed are only the ones present in the graph 
        importantNodes.push(link.domain().id());
      });
}
```

Is there something that I am missing or not understanding here?

Thank you!
