### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by mantoni** [VisualDataWeb/WebVOWL#53]
Hi,

I'm new to WebVOWL (and OWL in general) and was trying to find out what the "official" JSON format is? There are a few documents available, but no real documentation.

Also, I was asking myself what the relation to [JSON-LD](http://json-ld.org) is. At first sight the formats look somewhat similar. Is there a specific reason for not going with JSON-LD?

Thanks!

**Comment by linkvt** [comment]
Hi,

there is currently just the following template file available: [template.json](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/app/data/template.json).
As you can see it wasn't updated since a few months and lacks the types that can be used to specify the visual elements WebVOWL will use.

Since its a very tedious task to write this json file by hand, we recommend our official converter for ontologies: [OWL2VOWL](https://github.com/VisualDataWeb/OWL2VOWL). You can convert your ontologies very easily to the required json file without doing much by yourself.

There is also no intended relation to JSON-LD - the json structure we use is just a compact way to tell WebVOWL how the visualisation should look, because we can't interpret ontologies in WebVOWL.


Since WebVOWL and OWL2VOWL were academical projects in which we could invest just a limited amount of time, we focused on documenting just the important parts: the visualisation and the input interface of OWL2VOWL.
I hope however that this answer helps a bit.

**Comment by mantoni** [comment]
Thanks for explaining. The reason I'm asking is because I want to produce the JSON format directly instead of producing some other format and then shove it through OWL2VOWL. The `template.json` file will do, I think.
