### ISSUE TITLE
Embedding library

### ISSUE THREAD

**Issue by aw3s0me** [VisualDataWeb/WebVOWL#56]
Hi, guys. Is it possible to embed this library to some div and render by demand, prohibit user upload ontology and visualize ontology programatically by demand and remove all nodes from screen? Is there any api for this library, documentation?
Thanks!

**Comment by linkvt** [comment]
Hi,

we separated the webvowl-visualization from the [webvowl-app](http://vowl.visualdataweb.org/webvowl/index.html), since the visualization itself should be reusable.
You can find this separation in the [`src`](https://github.com/VisualDataWeb/WebVOWL/tree/master/src) directory, look especially at the [`app.js`](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/app/js/app.js) since it uses almost all available options, modules and other features the visualization provides.

You might try to build your own webvowl-app with the features and layout you need, but it's maybe easier if you take the current one and remove everything you won't need.
The visualized nodes and properties depend on the `data` you set on the `options`-object. If you don't set anything there, there won't be any nodes.

There is no API documentation and I can't provide you one now, because this was an educational project which is currently not under active development :grimacing:, but IMO the existing app should be enough to guide you in the right direction.

If you have further questions or find bugs etc., I will try to find some free time, but I hope this helps.
