### ISSUE TITLE
Questions regarding WebVOWL

### ISSUE THREAD

**Issue by narjesHN** [VisualDataWeb/WebVOWL#64]
I have a few problems and inquiries that I require assistance on.

Firstly, I am trying to edit the index file to have the correct dependency on the required scripts, as I have read the source code and there seems to be a few scripts that I cannot find them following their relative paths, therefore I am unsure as to whether they need to be modified or I need to drop these scripts into those paths from some other repository, the scripts that I am referring to are as follows:
- js/d3.min.js
- js/webvowl.js
- js/webvowl.app.js

Secondly, I would like my ontology(JSON file) to open by default upon opening the index file, and I was wondering how would I go around doing so?

Lastly, I am trying to add a feature which highlights/add some effects to the selected parent/sub class and its relevant classes (for example if there is a relationship between Class Animal and subclass Dog, and the user selects either 1, it will highlight both of them) or if the user selects a object property, it would highlight the domain and range class, so I was wondering which files/scripts should I be looking at to bring about these changes?

So far based on my initial testing, your visualization tool is the best & most interesting out there which fits my domain of work.

Thanks in advance and sorry for the long post 😄

**Comment by linkvt** [comment]
Hi,

these 3 scripts are generated by the build tool, it is described in the README.

You can *autolaunch* an ontology in the web by calling it via the #iri parameter like this:
http://visualdataweb.de/webvowl/#iri=http://visualdataweb.de/ontobench/ontology/ontology.ttl?features=objectprop
If you have a local ontology you need to convert it to a WebVOWL json with OWL2VOW. You can use the web version of WebVOWL for this (Ontology->Upload the Ontology then Export->Export as JSON). You have to adjust the [ontologyMenu.js](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/app/js/menu/ontologyMenu.js#L11) and the [index.html](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/index.html#L147) to auto load a local ontology/json file.

For the last question: Since a long time passed since opening this issue I will take a look at it if its still relevant.

Cheers and sorry for the long delay
