### ISSUE TITLE
Some predicates not being connected to domains or ranges in WebVOWL beta-0.5.2

### ISSUE THREAD

**Issue by andrewstellman** [VisualDataWeb/WebVOWL#65]
When I visualize the ontology from [pbprdf](https://github.com/andrewstellman/pbprdf), a few predicates are not being connected to their domains or ranges. 

You can reproduce the problem by loading the pbprdf ontology into WebVOWL: http://vowl.visualdataweb.org/webvowl/#iri=https://raw.githubusercontent.com/andrewstellman/pbprdf/master/generated/ontology.ttl

It visualizes a graph with an island in the lower left: 

![image](https://cloud.githubusercontent.com/assets/7516297/19418532/39c3c28e-938b-11e6-8ec6-4c704366e40e.png)

Here's a close-up:

![image](https://cloud.githubusercontent.com/assets/7516297/19418537/6a25693c-938b-11e6-8e1c-3fe480b16946.png)

Here's the TTL for the predicate that's selected in the close-up screenshot:

```
pbprdf:jumpBallAwayPlayer rdfs:label "The away player contesting the jump ball" ;
    rdfs:range pbprdf:Player ;
    rdfs:domain pbprdf:JumpBall ;
    a <http://www.w3.org/2002/07/owl#DatatypeProperty> .
```

The predicate is not connected to the range `pbprdf:Player` or the domain `pbprdf:JumpBall`, even though they are visualized elsewhere in the diagram. I checked the RDF pretty thoroughly, and I didn't see anything special about the four predicates that don't get connected to the rest of the graph.

**Comment by andrewstellman** [comment]
Incidentally, you guys did a fantastic job with WebVOWL. Nice work!

**Comment by steffen-l** [comment]
Thanks, Andrew. This issue should be fixed in the latest version of WebVOWL (OWL2VOWL). See here:
http://visualdataweb.de/webvowl/#iri=https://raw.githubusercontent.com/andrewstellman/pbprdf/master/generated/ontology.ttl

The latest version has some other minor bugs instead (unconnected classes and literals that should be linked) we are aware of and would like to fix before uploading it to vowl.visualdataweb.org
