### ISSUE TITLE
Function template with simple example?

### ISSUE THREAD

**Issue by nunobrito** [VisualDataWeb/WebVOWL#68]
Hello,

Thank you very much for sharing and developing WebVOWL. I am not an expert in ontologies, my focus would be using the graph visualization for a slightly different purpose.

Was trying to create a new data file using the template.json but it isn't getting loaded. Tried filling the expected values but I'm still missing to understand what is wrong.

Do you think it would be possible to provide a template that has a simple functional example with 2~3 nodes?

Many thanks.

**Comment by linkvt** [comment]
Hi,

I used [OntoBench](http://ontobench.visualdataweb.org/) to generate a simple ontology with an ObjectProperty and visualized it with WebVOWL: http://visualdataweb.de/webvowl/#iri=http://visualdataweb.de/ontobench/ontology/ontology.ttl?features=objectprop.
Just go to `Export` at the bottom and select `Export as JSON` and take a look at it.

You could also use the pregenerated ontologies like our [benchmark.json](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/app/data/benchmark.json) as example.

Cheers

**Comment by nunobrito** [comment]
Thank you very much! That was exactly what was needed. 

Perhaps worth putting that tiny example on the data folder too?

**Comment by linkvt** [comment]
Glad it helped 😄 

The data folder is only used for the *official* WebVOWL page located here: http://vowl.visualdataweb.org/webvowl/index.html. We suggest to use OWL2VOWL for the JSON creation because the manual creation is really error prone. Since it sounds like your problem is a special case I think it won't really help putting it there, but thanks for the suggestion!

BTW a tip if you create the JSON manually. You can skip objects in `classAttribute` and `propertyAttribute` and put everything in the object in the `class`/`property` array as seen here: [benchmark.json#L613](https://github.com/VisualDataWeb/WebVOWL/blob/master/src/app/data/benchmark.json#L613)

**Comment by nunobrito** [comment]
Thank you very much. It was possible to fully automate the generation thanks to your help. 👍
