### ISSUE TITLE
How to upgrade the project D3 to version 4, please give me some advice, thank you very much

### ISSUE THREAD

**Issue by yoyoma214** [VisualDataWeb/WebVOWL#83]
How to upgrade the project D3 to version 4, please give me some advice, thank you very much

**Comment by vitalis-wiens** [comment]
You can update the version via WebVOWL/package.json 
and change in the dependencies object    "d3": "^3.5.6",   to    "d3": "^4.5.0",
You will have to run npm install again.

But be careful since the api of d3 changed in the new version and thus the force layout may not 
behave as expected. Additionally the import and export of the node positions may fail.
