### ISSUE TITLE
Cannot load ontology from bag.basisregistraties.overheid.nl domain

### ISSUE THREAD

**Issue by jaw111** [VisualDataWeb/WebVOWL#95]
When trying to view this [BAG ontology](http://bag.basisregistraties.overheid.nl/def/bag) I get an error. Seems to be something with the certificates, the service to convert the ontology gives a HTTP 500 error:

http://visualdataweb.de/webvowl/convert?iri=https%3A%2F%2Fbag.basisregistraties.overheid.nl%2Fdef%2Fbag

`java.lang.RuntimeException: org.semanticweb.owlapi.io.OWLOntologyCreationIOException: OWLOntologyCreationIOException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target `

Can the certificates be added to the Java CA store?

**Comment by vitalis-wiens** [comment]
Hi, I`ve looked into this problem, it is more related to owl2vowl.
We are currently working on an update version for owl2vowl and webVOWL.

The fastest solution for you is to download owl2vowl and manually  convert the ontology to a json 
format for webvowl.  (while writing this, the issue is not fixed yet)

Regards Vitalis

**Comment by jaw111** [comment]
Hi @vitalis-wiens any progress on this issue? When possible we would like to use the public service.

**Comment by vitalis-wiens** [comment]
Hi, I think there is some tomcat issue regarding this. 
I could manually transfer the ontology running owl2vowl locally on my machine.

maybe you can use this converted file
webvowl allows you also to load json files, 
I hope this helps for now 

[bag.json.zip](https://github.com/VisualDataWeb/WebVOWL/files/1514171/bag.json.zip)

**Comment by steffen-l** [comment]
Yes, looks like we would have to add the certificate to our Java installation on the server hosting the public WebVOWL instance. Not sure if we want and would be able to do this.

BTW: You run into the same issue when trying to load the ontology with Protégé directly from the given URL. You would also have to download it and open it locally - otherwise, it is not loaded. It might thus be easier to remove the CA requirement on your side in this case. Or is it really needed?

Alternatively, you can link to the old (outdated) WebVOWL version that we are still hosting on a different server: http://vowl.visualdataweb.org/webvowl/old/#iri=https://bag.basisregistraties.overheid.nl/def/bag It has a different backend that doesn't care in this case, but it is an older version which is no longer actively maintained.

**Comment by erwinfolmer** [comment]
It is the Dutch government certificate...(and we are a government organisation, so we have to comply to that...and strangely enough it is not part of the standard certificate store...so we have to do this request more often outside the Netherlands; within the Netherlands this certificate is well known)
So hopefully you can add the certificate....(from the Dutch government perspective it will be appreciated. :))
