### ISSUE TITLE
Problems Loading Ontologies

### ISSUE THREAD

**Issue by megankatsumi** [VisualDataWeb/WebVOWL#98]
Hello,
I am interested in using your WebVOWL tool, and the example visualizations that I've seen look great. Unfortunately, I am unable to load some of the ontologies from my current project. The files work fine with other OWL tools (Protege for example), and are validated with the provided tool. I've tried both the IRIs as well as uploading the files directly. With the IRI I receive the output "There is no OWL input under the given IRI(https://w3id.org/icity/iCity-Change.owl). Please try to load the OWL file directly."
I had thought perhaps this has something to do with the redirect of the IRI, however with the file upload I receive the error: "{"timestamp":1503694002874,"status":500,"error":"Internal Server Error","exception":"java.lang.IllegalStateException","message":"java.lang.ArrayIndexOutOfBoundsException","path":"/webvowl/convert"}"
Any insight as to why this might be? Are there limitations beyond the file size on the types of ontologies that can be visualized?

Best,
Megan

**Comment by vitalis-wiens** [comment]
Thanks for the Issue
Unfortunately this is an error relating to OWL2VOWL and not WebVOWL
We will look into it, but I could transfer your ontology into the webvowl json format using the beta version of owl2vowl 
*Note* Not sure if translation into json was correct, since older version of owl2vowl  

You can try this file 

[res.zip](https://github.com/VisualDataWeb/WebVOWL/files/1264894/res.zip)

**Comment by vitalis-wiens** [comment]
Hello Megan, 

we have released a new version of WebVOWL and OWL2VOWL 

it provides now more loading and error descriptions  and is able to load your ontology. 

Kind Regards, 
Vitalis

**Comment by megankatsumi** [comment]
Hello Vitalis,
Thank you for letting me know. Looking forward to trying it out.

Megan

**Comment by mansimht** [comment]
Hi Vitalis,

Can you please share the ontology into the webvowl json format ? Because I am facing the same error while loading my ontology(ttl file) ?
Error:

{
"timestamp": 1673840626750,
"status": 500,
"error": "Internal Server Error",
"exception": "java.lang.IllegalStateException",
"message": "java.lang.NullPointerException",
"path": "/webvowl/convert"
}
